{{- if .Values.mysql.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app.kubernetes.io/instance: scuba
  name: scuba-app-db
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    DATABASE_URL: AgB8oCmqASpaLnjy6ot9PQSeo+w6gOy5WtS71iXG6njmmEhIf9dbAekCI/oH7ShfMC+++XIL1DVM9/IcNj9ERKbHyytERQmjoD4a3Mqj3AWT0PC+hJ93ExB+7DVR161hi0/jCoE/ausfi/aGEbPgA2FqUT0o8486vjOYFvqBeuPkwRV6UbYl8DcD907AyaVgQ5TPgPVTELCTC2JQxDnVl0njJhEpx7yzInH5bNIZGl4OPNCc0AM/V0GsKjfmJiI5a0Azyfhf8yYG2uccKFjHGs1uJwI+YS3FypqrCGgaOXWh9gZ3PJ4nv+UjNlAmifa7uha4nxrfYfqqZCVm7iM6/1JVrn0kEp9Apl+rG9htDpE8QHnPVmwpqCecJf4+rDx2tv76hxrVTmwmcxQCNh94dWNL6Rm8IFXt0czj8P2KCD7c0+MyK/nwsF0lNASzjEu0fkh0osJH41BToMCFMyQHdIUivsTTwwMDzigplBUhHwMxDGAzI9k1go6HZxiiZ0lz3n07OF44a7MXSAnnArkDJvefI0SKqCohHWlhM14hElC6/Cu4dtHluP8562tlPqrfC7czit0Hj55hdL7X3WizWCtZTNNCI4dAxalgYxL0kALYoS93wqCXg0e2aEAab+KQQyq0qNlhWw7cj2pUBma06YhMk7dlAYddLksLbnOU3oBz42UnHsNQaHIWo79fPV7UtwmoDZPs1tM/cTd8mF8KMSpSKdeoPpwdKNsAsSp6IHIbHn1rUUgyPVzR3bJOxei4x7llLxVp6SAbaI50YOphtmRBRnUH4vJGZfGxCXX3mW0O
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app.kubernetes.io/instance: scuba
      name: scuba-app-db
      namespace: {{ .Release.Namespace }}
{{- end }}
