apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
type: Opaque
stringData:
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | quote }}
  mysql-user: {{ .Values.mysql.auth.username | quote }}
  mysql-password: {{ .Values.mysql.auth.password | quote }}
  mysql-database: {{ .Values.mysql.auth.database | quote }}
