apiVersion: v1
kind: Secret
metadata:
  name: nutanix-loki-credentials
  namespace: kommander
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ${NUTANIX_OBJECTS_ACCESS_KEY}
  AWS_SECRET_ACCESS_KEY: ${NUTANIX_OBJECTS_SECRET_KEY}