# this secret will be applied on the workload cluster
# where the application you want to protect is running.
apiVersion: v1
data:
  ${SECRET_KEY_NAME}: ${PROFILEDATA}
kind: Secret
metadata:
  labels:
    kommanderType: connectorSecret
  name: ${NUTANIX_OBJECTS_SECRET}
  namespace: workload-cluster-namespace
type: Opaque
