apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-restore-from-backup
  namespace: miriam-backup-sealed
spec:
  from:
  - group: dataservices.nutanix.com
    kind: ApplicationSnapshotRestore
    namespace: miriam-scuba-sealed
  to:
  - group: dataservices.nutanix.com
    kind: ApplicationSnapshot
