apiVersion: dataservices.nutanix.com/v1alpha1
kind: Application
metadata:
  name: scuba-sealed
  namespace: miriam-scuba-sealed
spec:
  applicationSelector:
    resourceLabelSelectors:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/instance: scuba
  start: true
  useExistingConfig: false
---
apiVersion: dataservices.nutanix.com/v1alpha1
kind: ReplicationTarget
metadata:
  name: repl-to-nkp-wlc-b
  namespace: miriam-scuba-sealed
spec:
  namespaceName: miriam-backup-sealed
  remoteName: remote-nkp-wlc-b
---
apiVersion: scheduler.nutanix.com/v1alpha1
kind: JobScheduler
metadata:
  name: js-scuba-source
  namespace: miriam-scuba-sealed
spec:
  interval:
    minutes: 60
---
apiVersion: dataservices.nutanix.com/v1alpha1
kind: ProtectionPlan
metadata:
  name: pp-scuba-sealed-source-to-target
  namespace: miriam-scuba-sealed
spec:
  protectionType: async
  replicationConfigs:
  - replicationTargetName: repl-to-nkp-wlc-b
  retentionPolicy:
    retentionCount: 3
  scheduleName: js-scuba-source
---
apiVersion: dataservices.nutanix.com/v1alpha1
kind: AppProtectionPlan
metadata:
  name: appplan-scuba-sealed
  namespace: miriam-scuba-sealed
spec:
  applicationName: scuba-sealed
  protectionPlanNames:
  - pp-scuba-sealed-source-to-target
