apiVersion: dataservices.nutanix.com/v1alpha1
kind: Application
metadata:
  name: scuba
  namespace: miriam-scuba
spec:
  applicationSelector:
    resourceLabelSelectors:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/instance: scuba
  start: true
  useExistingConfig: false
---
apiVersion: dataservices.nutanix.com/v1alpha1
kind: ReplicationTarget
metadata:
  name: repl-to-nkp-wlc-a
  namespace: miriam-scuba
spec:
  namespaceName: miriam-backup
  remoteName: remote-nkp-wlc-a
---
apiVersion: scheduler.nutanix.com/v1alpha1
kind: JobScheduler
metadata:
  name: js-scuba-target
  namespace: miriam-scuba
spec:
  interval:
    minutes: 60
---
apiVersion: dataservices.nutanix.com/v1alpha1
kind: ProtectionPlan
metadata:
  name: pp-scuba-target-to-source
  namespace: miriam-scuba
spec:
  protectionType: async
  replicationConfigs:
  - replicationTargetName: repl-to-nkp-wlc-a
  retentionPolicy:
    retentionCount: 3
  scheduleName: js-scuba-target
---
apiVersion: dataservices.nutanix.com/v1alpha1
kind: AppProtectionPlan
metadata:
  name: appplan-scuba
  namespace: miriam-scuba
spec:
  applicationName: scuba
  protectionPlanNames:
  - pp-scuba-target-to-source
