apiVersion: v1
kind: Secret
metadata:
  name: velero-credentials-wlc-a
  namespace: nkp-flux-provisioned-phvwv-jjxpb
type: Opaque
data:
  cloud: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gWjBOSlNIOTVCNFdFOTIxUjRZTzUKYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0gU2JpSEhEaGhEaDJieW1GZXlZd2JaYkhwSWVOcDJ4eUpmalRXUGZlRAo=
